from typing import Protocol
from uuid import UUID


class TokenService(Protocol):
    def create_access_token(self, user_id: UUID) -> str: ...

    def parse_access_token(self, token: str) -> UUID | None: ...

    def create_refresh_token(self) -> str: ...

    def hash_refresh_token(self, token: str) -> str: ...
