import { apiClient } from "../../lib/apiClient";
import type { Job, JobInput, JobRequirement, JobsResult, JobStatus, RequirementInput } from "./types";
const base = (organizationId: string) => `/api/v1/organizations/${organizationId}/jobs`;
export const listJobs = (organizationId: string, params: { page: number; status?: JobStatus; search?: string }) => { const query = new URLSearchParams({ page: String(params.page), page_size: "20", ...(params.status ? { status: params.status } : {}), ...(params.search ? { search: params.search } : {}) }); return apiClient<JobsResult>(`${base(organizationId)}?${query}`); };
export const getJob = (organizationId: string, jobId: string) => apiClient<{ job: Job }>(`${base(organizationId)}/${jobId}`);
export const createJob = (organizationId: string, input: JobInput) => apiClient<{ job: Job }>(base(organizationId), { method: "POST", body: JSON.stringify(input) });
export const updateJob = (organizationId: string, jobId: string, input: Partial<JobInput>) => apiClient<{ job: Job }>(`${base(organizationId)}/${jobId}`, { method: "PATCH", body: JSON.stringify(input) });
export const closeJob = (organizationId: string, jobId: string) => apiClient<{ job: Job }>(`${base(organizationId)}/${jobId}/close`, { method: "POST" });
export const archiveJob = (organizationId: string, jobId: string) => apiClient<{ job: Job }>(`${base(organizationId)}/${jobId}/archive`, { method: "POST" });
const requirementBase = (organizationId: string, jobId: string) => `${base(organizationId)}/${jobId}/requirements`;
export const listRequirements = (organizationId: string, jobId: string) => apiClient<{ items: JobRequirement[] }>(requirementBase(organizationId, jobId));
export const createRequirement = (organizationId: string, jobId: string, input: RequirementInput) => apiClient<{ requirement: JobRequirement }>(requirementBase(organizationId, jobId), { method: "POST", body: JSON.stringify(input) });
export const updateRequirement = (organizationId: string, jobId: string, requirementId: string, input: RequirementInput) => apiClient<{ requirement: JobRequirement }>(`${requirementBase(organizationId, jobId)}/${requirementId}`, { method: "PATCH", body: JSON.stringify(input) });
export const deleteRequirement = (organizationId: string, jobId: string, requirementId: string) => apiClient<{ deleted: boolean }>(`${requirementBase(organizationId, jobId)}/${requirementId}`, { method: "DELETE" });
export const reorderRequirements = (organizationId: string, jobId: string, requirementIds: string[]) => apiClient<{ items: JobRequirement[] }>(`${requirementBase(organizationId, jobId)}/reorder`, { method: "PUT", body: JSON.stringify({ requirement_ids: requirementIds }) });
export const submitJob = (organizationId: string, jobId: string) => apiClient<{ job: Job }>(`${base(organizationId)}/${jobId}/submit-for-approval`, { method: "POST" });
export const approveJob = (organizationId: string, jobId: string) => apiClient<{ job: Job }>(`${base(organizationId)}/${jobId}/approve`, { method: "POST" });
export const returnJobToDraft = (organizationId: string, jobId: string, review_note: string) => apiClient<{ job: Job }>(`${base(organizationId)}/${jobId}/return-to-draft`, { method: "POST", body: JSON.stringify({ review_note }) });
