from typing import Protocol


class ResumeStorage(Protocol):
    async def upload(self, key: str, content: bytes) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def signed_url(self, key: str, expires: int) -> str: ...
