import { BriefcaseBusiness, CalendarDays, Globe2, Mail, MapPin, Phone, UserRound } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { ActivityTimeline } from "../components/candidates/ActivityTimeline";
import { ApplicationHistory } from "../components/candidates/ApplicationHistory";
import { CommunicationsSection } from "../components/candidates/CommunicationsSection";
import { OfferOnboardingSection } from "../components/candidates/OfferOnboardingSection";
import { ResumeSection } from "../components/candidates/ResumeSection";
import { ActionMenu } from "../components/common/ActionMenu";
import { DetailBack, DetailHeader, DetailMetaGrid, DetailPage, DetailSection } from "../components/common/DetailPage";
import { AppShell } from "../components/layout/AppShell";
import { useCandidate } from "../features/candidates/queries";
import { useOrganization } from "../features/organizations/OrganizationProvider";
export function CandidateDetailPage() {
 const {candidateId=""}=useParams(); const navigate=useNavigate(); const {organization}=useOrganization(); const org=organization?.organization.id??""; const {data,isLoading,error}=useCandidate(org,candidateId);
 if(isLoading)return <AppShell title="Candidate details"><p>Loading candidate…</p></AppShell>; if(!data)return <AppShell title="Candidate details"><p>{error?.message??"Candidate was not found."}</p></AppShell>;
 const candidate=data.candidate, manage=["admin","recruiter"].includes(organization?.role??""), view=["admin","recruiter","hiring_manager"].includes(organization?.role??""), approver=["admin","hiring_manager"].includes(organization?.role??"");
 const facts=[{icon:Mail,label:"Email",value:candidate.email??"Not provided"},{icon:Phone,label:"Phone",value:candidate.phone??"Not provided"},{icon:MapPin,label:"Address",value:candidate.location??"Not provided"},{icon:BriefcaseBusiness,label:"Current title",value:candidate.current_title??"Not provided"},{icon:Globe2,label:"Experience",value:candidate.years_of_experience===null?"Not specified":`${candidate.years_of_experience} years`},{icon:CalendarDays,label:"Profile created",value:new Date(candidate.created_at).toLocaleDateString()}];
 const education=candidate.education?.length?<div className="mt-3 grid gap-3 sm:grid-cols-2">{candidate.education.map((item,index)=><div key={`${item.degree}-${index}`} className="rounded-xl bg-[var(--color-elevated)] p-4"><p className="font-semibold">{item.degree}</p><p className="mt-1 text-sm text-[var(--color-muted)]">{item.institution}{item.field_of_study?` · ${item.field_of_study}`:""}</p></div>)}</div>:<div className="mt-3 rounded-xl border border-dashed border-[var(--color-border)] px-4 py-3 text-sm text-[var(--color-muted)]">No education records added.</div>;
 return <AppShell title="Candidate details"><DetailPage><DetailBack to="/hiring?tab=candidates">Back to Candidates</DetailBack><DetailHeader icon={UserRound} title={candidate.full_name} subtitle={candidate.current_title?`${candidate.current_title} · ${candidate.email??"Contact details not provided"}`:candidate.email??"Candidate profile"} badge={<span className="rounded-full bg-[var(--color-sage)] px-2.5 py-1 text-xs font-semibold text-[var(--color-teal)]">Candidate</span>} actions={manage?<ActionMenu label={`Actions for ${candidate.full_name}`} items={[{label:"Edit candidate",onSelect:()=>navigate(`/candidates/${candidate.id}/edit`)}]}/>:undefined}><DetailMetaGrid items={facts}/></DetailHeader><DetailSection title="" description="" bare><section><h3 className="text-base font-semibold">Profile summary</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-[var(--color-muted)]">{candidate.summary??"No professional summary added."}</p></section><section className="mt-6 border-t border-[var(--color-border)] pt-5"><h3 className="text-base font-semibold">Education</h3><p className="mt-1 text-sm text-[var(--color-muted)]">Academic qualifications and professional certifications.</p>{education}</section><section className="mt-6 border-t border-[var(--color-border)] pt-5"><h3 className="text-base font-semibold">Resume</h3><p className="mt-1 text-sm text-[var(--color-muted)]">View the candidate’s available resume.</p><ResumeSection organizationId={org} candidateId={candidate.id} editable={false} embedded/></section></DetailSection>{view&&<><ApplicationHistory organizationId={org} candidateId={candidate.id}/><OfferOnboardingSection organizationId={org} candidateId={candidate.id} manageable={manage} approver={approver}/><CommunicationsSection candidateId={candidate.id} candidateName={candidate.full_name}/><ActivityTimeline organizationId={org} candidateId={candidate.id}/></>}</DetailPage></AppShell>;
}
