import { useEffect, useState, type FormEvent } from "react";
import { FaPlusCircle } from "react-icons/fa";
import { Link, useSearchParams } from "react-router-dom";
import { Table } from "../components/common/Table";
import { PrimaryButton } from "../components/ui/PrimaryButton";
import { SearchInput } from "../components/ui/SearchInput";
import { useCandidates } from "../features/candidates/queries";
import { useOrganization } from "../features/organizations/OrganizationProvider";

const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
export function CandidatesList() {
  const { organization } = useOrganization(); const org = organization?.organization.id ?? ""; const [params, setParams] = useSearchParams(); const [search, setSearch] = useState(params.get("search") ?? ""); const page = Number(params.get("page") ?? 1); const { data, isLoading, error, refetch } = useCandidates(org, page, params.get("search") || undefined); const canEdit = ["admin", "recruiter"].includes(organization?.role ?? "");
  useEffect(() => setSearch(params.get("search") ?? ""), [params]);
  const apply = (event: FormEvent) => { event.preventDefault(); setParams(Object.fromEntries(Object.entries({ tab: "candidates", page: "1", search }).filter(([, value]) => value))); }; const clear = () => { setSearch(""); setParams({ tab: "candidates" }); };
  const row = (candidate: NonNullable<typeof data>["items"][number]) => <><td className="px-5 py-4"><Link to={`/candidates/${candidate.id}`} className="flex items-center gap-3 font-semibold transition hover:text-[var(--color-navy)]"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[var(--color-sage)] text-sm text-[var(--color-teal)]">{initials(candidate.full_name)}</span><span><strong className="block">{candidate.full_name}</strong><span className="mt-1 block text-sm font-normal text-[var(--color-muted)]">{candidate.current_title ?? "Title not added"}</span></span></Link></td><td className="px-5 py-4 text-sm text-[var(--color-muted)]">{candidate.location?.trim() || "Not specified"}</td><td className="px-5 py-4 text-sm text-[var(--color-muted)]">{candidate.years_of_experience === null ? "Not specified" : `${candidate.years_of_experience} years`}</td><td className="px-5 py-4 text-right"><span className="hc-availability-badge inline-flex min-h-7 min-w-24 items-center justify-center rounded-full bg-[var(--color-sage)] px-4 py-1.5 text-xs font-semibold">Available</span></td></>;
  return <><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[var(--color-teal)]">Hiring workspace</p><h1 className="mt-2 text-3xl font-semibold">Candidates</h1><p className="mt-2 text-[var(--color-muted)]">Keep the people you meet organized before matching them to a role.</p></div>{canEdit && <Link to="/candidates/new" className="hc-primary-action inline-flex items-center gap-2 px-4 py-2.5 text-sm"><FaPlusCircle size={22} aria-hidden="true"/>Add Candidate</Link>}</header><section className="mt-8 rounded-2xl border bg-[var(--color-surface)] p-4 shadow-[var(--shadow-card)]"><form onSubmit={apply} className="flex gap-3"><SearchInput value={search} onChange={setSearch} onClear={clear} placeholder="Search by name, title, or location" ariaLabel="Search candidates by name, title, or location"/><PrimaryButton type="submit">Search</PrimaryButton></form>{isLoading && <div className="mt-4 h-20 animate-pulse rounded-xl bg-[var(--color-canvas)]"/>}{error && <p className="mt-4 text-sm text-[var(--color-red)]">{error.message} <button onClick={() => refetch()} className="underline">Retry</button></p>}{data && <div className="mt-4"><Table columns={[{ label: "Candidate" }, { label: "Location" }, { label: "Experience" }, { label: "Status", className: "text-right" }]} items={data.items} rowKey={(candidate) => candidate.id} renderRow={row} empty={<div className="px-5 py-12 text-center"><h2 className="font-semibold">No candidates found</h2><p className="mt-2 text-sm text-[var(--color-muted)]">Add a candidate to begin building your talent pool.</p></div>}/></div>}</section></>;
}
