import { useState } from "react";
import { FaPlusCircle } from "react-icons/fa";
import { Link, useSearchParams } from "react-router-dom";
import { Table } from "../components/common/Table";
import { JobStatusBadge } from "../components/jobs/JobStatusBadge";
import { Dropdown } from "../components/ui/Dropdown";
import { useJobs } from "../features/jobs/queries";
import { useOrganization } from "../features/organizations/OrganizationProvider";
import type { Job, JobStatus } from "../features/jobs/types";
import { displayLabel } from "../lib/labels";

const statuses: JobStatus[] = ["draft", "pending_approval", "approved", "closed", "archived"];
export function JobsList() {
  const { organization } = useOrganization(); const [params, setParams] = useSearchParams(); const [search, setSearch] = useState(params.get("search") ?? ""); const page = Number(params.get("page") ?? 1); const status = params.get("status") as JobStatus | null; const { data, isLoading, error, refetch } = useJobs(organization?.organization.id ?? "", page, status ?? undefined, params.get("search") ?? undefined); const manager = organization?.role === "admin" || organization?.role === "recruiter";
  const update = (next: Record<string, string>) => setParams(Object.fromEntries(Object.entries({ ...Object.fromEntries(params), ...next }).filter(([, value]) => value))); const clear = () => { setSearch(""); setParams({ tab: "jobs" }); };
  const row = (job: Job) => <><td className="px-5 py-4"><Link to={`/jobs/${job.id}`} className="font-semibold transition hover:text-[var(--color-navy)]">{job.title}</Link><p className="mt-1 line-clamp-1 text-sm text-[var(--color-muted)]">{job.description?.trim() || "Details not added"}</p></td><td className="px-5 py-4 text-sm text-[var(--color-muted)]">{job.location?.trim() || "Not specified"}</td><td className="px-5 py-4 text-sm text-[var(--color-muted)]">{displayLabel(job.employment_type) || "Not specified"}</td><td className="px-5 py-4 text-sm text-[var(--color-muted)]">{displayLabel(job.workplace_type) || "Not specified"}</td><td className="px-5 py-4 text-right"><JobStatusBadge status={job.status}/></td></>;
  return <><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[var(--color-teal)]">Hiring workspace</p><h1 className="mt-2 text-3xl font-semibold">Jobs</h1><p className="mt-2 text-[var(--color-muted)]">Create and manage the roles your team is hiring for.</p></div>{manager && <Link to="/hiring/jobs/new" className="hc-primary-action inline-flex items-center gap-2 px-4 py-2.5 text-sm"><FaPlusCircle size={22} aria-hidden="true"/>Create Job</Link>}</header><section className="mt-8 rounded-2xl border bg-[var(--color-surface)] p-4 shadow-[var(--shadow-card)]"><div className="flex flex-wrap gap-3"><form onSubmit={event => { event.preventDefault(); update({ search, page: "1" }); }} className="flex flex-1 gap-2"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search job titles" className="min-w-48 flex-1 rounded-xl border px-3 py-2"/><button className="rounded-xl border px-3 py-2 text-sm font-semibold">Search</button></form><div className="w-44"><Dropdown value={status ?? ""} onChange={value => update({ status: value, page: "1" })} options={[{ value: "", label: "All Statuses" }, ...statuses.map(item => ({ value: item, label: displayLabel(item) }))]}/></div>{(status || params.get("search")) && <button onClick={clear} className="px-2 text-sm font-semibold text-[var(--color-muted)]">Clear filters</button>}</div>{isLoading && <div className="mt-4 h-24 animate-pulse rounded-xl bg-[var(--color-canvas)]"/>}{error && <div className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-[var(--color-red)]">{error.message} <button onClick={() => refetch()} className="ml-2 font-semibold underline">Retry</button></div>}{data && <div className="mt-4"><Table columns={[{ label: "Job" }, { label: "Location" }, { label: "Employment" }, { label: "Workplace" }, { label: "Status", className: "text-right" }]} items={data.items} rowKey={(job) => job.id} renderRow={row} empty={<div className="px-5 py-12 text-center"><h2 className="font-semibold">No jobs found</h2><p className="mt-2 text-sm text-[var(--color-muted)]">Create a job to begin building your hiring workspace.</p></div>}/></div>}</section></>;
}
