import { useMutation, useQuery } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import { apiClient } from "../lib/apiClient";
import type { Offer } from "../features/offers/api";

export function OfferResponsePage() {
  const { token = "" } = useParams(); const offer = useQuery({ queryKey: ["public-offer", token], queryFn: () => apiClient<{ offer: Offer }>(`/api/v1/offers/${token}`), enabled: !!token }); const response = useMutation({ mutationFn: (value: "accepted" | "declined") => apiClient<{ offer: Offer }>(`/api/v1/offers/${token}/response`, { method: "POST", body: JSON.stringify({ response: value }) }), onSuccess: () => offer.refetch() }); const item = offer.data?.offer;
  if (offer.isLoading) return <main className="mx-auto max-w-xl p-8">Loading your offer…</main>; if (!item) return <main className="mx-auto max-w-xl p-8">This offer is unavailable.</main>;
  return <main className="mx-auto max-w-xl p-6 sm:p-12"><section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 shadow-[var(--shadow-soft)]"><p className="text-sm font-semibold text-[var(--color-teal)]">Hiring Compass</p><h1 className="mt-2 text-2xl font-semibold">Offer for {item.job_title}</h1><dl className="mt-6 grid gap-4 text-sm"><div><dt className="text-[var(--color-muted)]">Salary</dt><dd className="font-semibold">{item.currency} {item.salary}</dd></div><div><dt className="text-[var(--color-muted)]">Start date</dt><dd>{item.start_date}</dd></div><div><dt className="text-[var(--color-muted)]">Location</dt><dd>{item.work_location}</dd></div><div><dt className="text-[var(--color-muted)]">Terms</dt><dd className="whitespace-pre-wrap">{item.additional_terms || "No additional terms."}</dd></div></dl>{item.status === "sent" ? <div className="mt-8 flex gap-3"><button className="hc-primary-action" disabled={response.isPending} onClick={() => response.mutate("accepted")}>Accept offer</button><button className="rounded-full border border-[var(--color-border)] px-4 py-2 text-sm font-semibold" disabled={response.isPending} onClick={() => response.mutate("declined")}>Decline</button></div> : <p className="mt-8 rounded-xl bg-[var(--color-elevated)] p-4 text-sm">This offer has been {item.status}.</p>}{response.error && <p role="alert" className="mt-4 text-sm text-[var(--color-red)]">{response.error.message}</p>}</section></main>;
}
