import { Building2, CheckCircle2, Compass, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Dropdown } from "../components/ui/Dropdown";
import { Toast } from "../components/ui/Toast";
import { AppShell } from "../components/layout/AppShell";
import { addMember, listMembers, updateMember, updateOrganization } from "../features/organizations/api";
import { useOrganization } from "../features/organizations/OrganizationProvider";
import type { Member } from "../features/organizations/types";

const roles = ["admin", "recruiter", "hiring_manager", "interviewer"];
const roleLabel = (role: string) => role.split("_").map((part) => part[0].toUpperCase() + part.slice(1)).join(" ");
const roleOptions = roles.map((value) => ({ value, label: roleLabel(value) }));
const initials = (name: string) => name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();

export function OrganizationSettingsPage() {
  const { organization, refresh } = useOrganization(); const [name, setName] = useState(organization?.organization.name ?? ""); const [members, setMembers] = useState<Member[]>([]); const [notice, setNotice] = useState<{ text: string; tone: "success" | "error" } | null>(null); const [saving, setSaving] = useState(false); const admin = organization?.role === "admin";
  const load = () => organization && listMembers(organization.organization.id).then((result) => setMembers(result.members)).catch((error: Error) => setNotice({ text: error.message, tone: "error" }));
  useEffect(() => { if (admin) load(); }, [organization?.organization.id, admin]);
  const save = async () => { if (!organization || !name.trim()) return; setSaving(true); try { await updateOrganization(organization.organization.id, name.trim()); await refresh(); setNotice({ text: "Organization profile saved.", tone: "success" }); } catch (error) { setNotice({ text: error instanceof Error ? error.message : "Could not save organization profile.", tone: "error" }); } finally { setSaving(false); } };
  return <AppShell title="Settings"><section className="mx-auto max-w-5xl"><header><p className="text-sm font-semibold text-[var(--color-teal)]">Recruitment workspace</p><h1 className="mt-2 text-3xl font-semibold">Settings</h1><p className="mt-2 text-[var(--color-muted)]">Manage {organization?.organization.name ?? "your organization"} and the people who hire with you.</p></header>{!admin && <p className="mt-7 rounded-2xl border border-[var(--color-border)] bg-[var(--color-sage)] p-4 text-sm text-[var(--color-teal)]">You have read-only access to this organization. Contact an admin to make workspace changes.</p>}{admin && <><OrganizationProfile name={name} setName={setName} saving={saving} save={save}/><MemberPanel organizationId={organization!.organization.id} members={members} reload={load} notify={setNotice}/></>}<RecruiterGuide/>{notice && <Toast message={notice.text} tone={notice.tone} onClose={() => setNotice(null)}/>}</section></AppShell>;
}

function OrganizationProfile({ name, setName, saving, save }: { name: string; setName: (value: string) => void; saving: boolean; save: () => void }) { const dirty = Boolean(name.trim()); return <section className="mt-9 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 sm:p-7"><div className="flex items-start gap-4"><span className="grid size-10 place-items-center rounded-xl bg-[var(--color-elevated)] text-[var(--color-navy)]"><Building2 size={20}/></span><div><h2 className="text-xl font-semibold">Organization</h2><p className="mt-1 text-sm text-[var(--color-muted)]">Manage the basic details of your hiring workspace.</p></div></div><label className="mt-7 block max-w-xl text-sm font-medium">Organization Name<input value={name} onChange={(event) => setName(event.target.value)} className="hc-form-control mt-2 bg-[var(--color-elevated)]"/></label><button type="button" disabled={saving || !name.trim()} onClick={save} className="hc-primary-action mt-6 inline-flex min-h-11 items-center px-5 text-sm font-semibold disabled:opacity-50">{saving ? "Saving…" : "Save Changes"}</button></section>; }

function MemberPanel({ organizationId, members, reload, notify }: { organizationId: string; members: Member[]; reload: () => void; notify: (notice: { text: string; tone: "success" | "error" }) => void }) { const [email, setEmail] = useState(""); const [role, setRole] = useState("recruiter"); const [adding, setAdding] = useState(false); const add = async (event: React.FormEvent) => { event.preventDefault(); setAdding(true); try { await addMember(organizationId, email, role); setEmail(""); reload(); notify({ text: "Team member added.", tone: "success" }); } catch (error) { notify({ text: error instanceof Error ? error.message : "Could not add team member.", tone: "error" }); } finally { setAdding(false); } }; const change = async (member: Member, body: object) => { try { await updateMember(organizationId, member.membership.id, body); reload(); notify({ text: "Member settings updated.", tone: "success" }); } catch (error) { notify({ text: error instanceof Error ? error.message : "Could not update team member.", tone: "error" }); } };
  return <section className="mt-7 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><span className="grid size-10 place-items-center rounded-xl bg-[var(--color-elevated)] text-[var(--color-navy)]"><Users size={20}/></span><div><h2 className="text-xl font-semibold">Team members</h2><p className="mt-1 text-sm text-[var(--color-muted)]">Invite teammates to collaborate on jobs, candidates, and interviews.</p></div></div><span className="rounded-full bg-[var(--color-elevated)] px-3 py-1 text-sm font-semibold text-[var(--color-navy)]">{members.length} members</span></div><form onSubmit={add} className="mt-7 grid gap-3 rounded-xl bg-[var(--color-elevated)] p-4 sm:grid-cols-[minmax(0,1fr)_13rem_auto]"><label className="sr-only" htmlFor="member-email">Email address</label><input id="member-email" required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="colleague@company.com" className="hc-form-control bg-[var(--color-surface)]"/><Dropdown label="" value={role} options={roleOptions} onChange={setRole}/><button disabled={adding} className="hc-primary-action min-h-11 px-5 text-sm font-semibold disabled:opacity-50">{adding ? "Adding…" : "Add Member"}</button></form><p className="mt-4 rounded-xl bg-[var(--color-elevated)] px-4 py-3 text-sm text-[var(--color-muted)]">Admins cannot change their own role or active status.</p><div className="mt-5 divide-y divide-[var(--color-border)]">{members.map((member) => <article key={member.membership.id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[var(--color-elevated)] text-sm font-semibold text-[var(--color-navy)]">{initials(member.user.display_name)}</span><div className="min-w-0"><p className="font-semibold">{member.user.display_name}</p><p className="truncate text-sm text-[var(--color-muted)]">{member.user.email}</p></div></div><div className="flex flex-wrap items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${member.membership.is_active ? "bg-[var(--color-elevated)] text-[var(--color-navy)]" : "bg-[var(--color-elevated)] text-[var(--color-muted)]"}`}>{member.membership.is_active ? "Active" : "Inactive"}</span><div className="w-40"><Dropdown label="" value={member.membership.role} options={roleOptions} onChange={(value) => change(member, { role: value })}/></div><button type="button" onClick={() => change(member, { is_active: !member.membership.is_active })} className="rounded-full border border-[var(--color-border)] px-4 py-2 text-sm font-semibold">{member.membership.is_active ? "Deactivate" : "Activate"}</button></div></article>)}</div></section>; }

function RecruiterGuide() { return <section className="mt-7 rounded-2xl border border-[var(--color-border)] bg-[var(--color-elevated)] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[var(--color-surface)] text-[var(--color-navy)]"><Compass size={18}/></span><div><p className="text-sm font-semibold text-[var(--color-teal)]">Recruiter guide</p><h2 className="mt-1 font-semibold">From job setup to onboarding</h2><p className="mt-1 text-sm text-[var(--color-muted)]">Review the complete hiring workflow step by step.</p></div></div><Link to="/settings/guide" className="hc-primary-action inline-flex items-center text-sm">Open guide</Link></div></section>; }
