import { useEffect, useState } from "react";
import { AppShell } from "../components/layout/AppShell";
import { addMember, listMembers, updateMember, updateOrganization } from "../features/organizations/api";
import { useOrganization } from "../features/organizations/OrganizationProvider";
import type { Member } from "../features/organizations/types";
const roles = ["admin", "recruiter", "hiring_manager", "interviewer"];
const roleLabel = (role: string) => role.split("_").map((part) => part[0].toUpperCase() + part.slice(1)).join(" ");
export function OrganizationSettingsPage() {
  const { organization, refresh } = useOrganization(); const [name, setName] = useState(organization?.organization.name ?? ""); const [members, setMembers] = useState<Member[]>([]); const [message, setMessage] = useState(""); const admin = organization?.role === "admin";
  const load = () => organization && listMembers(organization.organization.id).then((r) => setMembers(r.members)).catch((e: Error) => setMessage(e.message));
  useEffect(() => { if (admin) load(); }, [organization?.organization.id]);
  const save = async () => { if (!organization) return; try { await updateOrganization(organization.organization.id, name); await refresh(); setMessage("Organization updated."); } catch (e) { setMessage(e instanceof Error ? e.message : "Update failed."); } };
  return <AppShell title="Settings"><section className="max-w-3xl"><p className="text-sm font-semibold text-[var(--color-teal)]">Organization settings</p><h1 className="mt-2 text-3xl font-semibold">{organization?.organization.name}</h1>{!admin && <p className="mt-4 rounded-xl bg-[var(--color-sage)] p-4 text-sm">You have read-only access to this organization.</p>}{admin && <><div className="mt-7 rounded-2xl border bg-white p-6"><label className="text-sm font-medium">Organization name<input value={name} onChange={(e) => setName(e.target.value)} className="mt-2 w-full rounded-xl border p-3" /></label><button onClick={save} className="mt-4 rounded-xl bg-[var(--color-navy)] px-4 py-2 text-sm font-semibold text-white">Save changes</button></div><MemberPanel organizationId={organization!.organization.id} members={members} reload={load} /></>}{message && <p className="mt-4 text-sm">{message}</p>}</section></AppShell>;
}
function MemberPanel({ organizationId, members, reload }: { organizationId: string; members: Member[]; reload: () => void }) { const [email, setEmail] = useState(""); const [role, setRole] = useState("recruiter"); const [message, setMessage] = useState(""); const add = async (e: React.FormEvent) => { e.preventDefault(); try { await addMember(organizationId, email, role); setEmail(""); reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not add member."); } }; const change = async (member: Member, body: object) => { try { await updateMember(organizationId, member.membership.id, body); reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update member."); } }; return <div className="mt-6 rounded-2xl border bg-white p-6"><h2 className="text-lg font-semibold">Members</h2><form onSubmit={add} className="mt-4 flex flex-wrap gap-2"><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="colleague@example.com" className="rounded-xl border px-3 py-2" /><select value={role} onChange={(e) => setRole(e.target.value)} className="rounded-xl border px-3 py-2">{roles.map((r) => <option key={r} value={r}>{roleLabel(r)}</option>)}</select><button className="rounded-xl bg-[var(--color-navy)] px-4 py-2 text-sm font-semibold text-white">Add member</button></form>{message && <p className="mt-3 text-sm text-red-700">{message}</p>}<div className="mt-5 space-y-3">{members.map((m) => <div key={m.membership.id} className="flex flex-wrap items-center justify-between gap-3 border-t pt-3"><div><p className="font-medium">{m.user.display_name}</p><p className="text-sm text-[var(--color-muted)]">{m.user.email}</p></div><div className="flex gap-2"><select value={m.membership.role} onChange={(e) => change(m, { role: e.target.value })} className="rounded-lg border px-2 py-1">{roles.map((r) => <option key={r} value={r}>{roleLabel(r)}</option>)}</select><button disabled={!m.membership.is_active} onClick={() => change(m, { is_active: false })} className="rounded-lg border px-2 py-1 text-sm">{m.membership.is_active ? "Deactivate" : "Inactive"}</button></div></div>)}</div></div>; }
