import { BriefcaseBusiness, ChevronRight, ClipboardCheck, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";
import { useQueries } from "@tanstack/react-query";
import { AppShell } from "../components/layout/AppShell";
import { ReadinessCard } from "../components/dashboard/ReadinessCard";
import { useAuth } from "../features/auth/AuthProvider";
import { useOrganization } from "../features/organizations/OrganizationProvider";
import { listJobApplications } from "../features/applications/api";
import { useCandidates } from "../features/candidates/queries";
import { useJobs } from "../features/jobs/queries";

const statusLabel = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export function OverviewPage() {
  const { user } = useAuth(); const { organization } = useOrganization(); const organizationId = organization?.organization.id ?? "";
  const jobs = useJobs(organizationId, 1); const candidates = useCandidates(organizationId, 1); const jobItems = jobs.data?.items ?? [];
  const applicationQueries = useQueries({ queries: jobItems.map((job) => ({ queryKey: ["applications", organizationId, "job", job.id], queryFn: () => listJobApplications(organizationId, job.id), enabled: Boolean(organizationId) })) });
  const applications = applicationQueries.flatMap((query) => query.data?.items ?? []); const activeJobs = jobItems.filter((job) => job.status === "approved"); const firstName = user?.display_name?.split(" ")[0] ?? "there";
  const pipeline = (["new", "shortlisted", "on_hold", "rejected"] as const).map((status) => ({ status, count: applications.filter((application) => application.status === status).length })); const maxPipeline = Math.max(1, ...pipeline.map(({ count }) => count));
  const metrics = [
    { label: "Open roles", value: activeJobs.length, detail: "Approved and live", icon: BriefcaseBusiness, tone: "bg-[var(--color-sage)] text-[var(--color-navy)]" },
    { label: "Candidates", value: candidates.data?.pagination.total ?? 0, detail: "In your workspace", icon: UsersRound, tone: "bg-[var(--color-sage)] text-[var(--color-teal)]" },
    { label: "Applications", value: applications.filter((application) => application.status !== "rejected").length, detail: "Currently in motion", icon: ClipboardCheck, tone: "bg-[color-mix(in_srgb,var(--color-amber)_18%,transparent)] text-[var(--color-amber)]" },
    { label: "Shortlisted", value: pipeline.find(({ status }) => status === "shortlisted")?.count ?? 0, detail: "Ready for review", icon: ChevronRight, tone: "bg-[var(--color-sage)] text-[var(--color-teal)]" },
  ];
  return <AppShell title="Overview">
    <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-[var(--color-teal)]">Analytics overview</p><h1 className="mt-1 text-3xl font-semibold tracking-tight sm:text-4xl">Good to see you, {firstName}.</h1><p className="mt-2 text-sm text-[var(--color-muted)]">A clear view of the hiring work moving through {organization?.organization.name ?? "your workspace"}.</p></div><Link to="/jobs/new" className="inline-flex items-center justify-center rounded-xl bg-[var(--color-navy)] px-4 py-2.5 text-sm font-semibold text-white shadow-[var(--shadow-card)]">Create job</Link></section>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Hiring snapshot">{metrics.map(({ label, value, detail, icon: Icon, tone }) => <article key={label} className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 shadow-[var(--shadow-card)]"><span className={`grid size-9 place-items-center rounded-full ${tone}`}><Icon size={17} aria-hidden="true" /></span><p className="mt-5 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-sm font-medium">{label}</p><p className="mt-1 text-xs text-[var(--color-muted)]">{detail}</p></article>)}</section>
    <section className="mt-8 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 shadow-[var(--shadow-card)]"><div><p className="text-sm font-semibold">Hiring momentum</p><p className="mt-1 text-xs text-[var(--color-muted)]">Applications by current stage</p></div><div className="mt-8 space-y-5">{pipeline.map(({ status, count }) => <div key={status} className="grid grid-cols-[112px_1fr_28px] items-center gap-3 text-sm"><span className="text-[var(--color-muted)]">{statusLabel(status)}</span><div className="h-2 overflow-hidden rounded-full bg-[var(--color-canvas)]"><div className="h-full rounded-full bg-[var(--color-navy)] transition-all" style={{ width: `${(count / maxPipeline) * 100}%` }} /></div><strong className="text-right">{count}</strong></div>)}</div><p className="mt-8 rounded-xl bg-[var(--color-canvas)] px-4 py-3 text-sm text-[var(--color-muted)]">Every decision stays connected to the role, application, and candidate context.</p></article><article className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 shadow-[var(--shadow-card)]"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Hiring focus</p><p className="mt-1 text-xs text-[var(--color-muted)]">What to move forward next</p></div><ClipboardCheck className="text-[var(--color-teal)]" size={20} aria-hidden="true" /></div><div className="mt-7 space-y-4">{[`${activeJobs.length} open ${activeJobs.length === 1 ? "role" : "roles"} need candidate review`, `${applications.filter((application) => application.status === "new").length} new applications are ready to assess`, `${jobItems.filter((job) => ["draft", "pending_approval"].includes(job.status)).length} job drafts need approval`].map((item, index) => <div key={item} className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-[var(--color-sage)] text-xs font-semibold text-[var(--color-teal)]">0{index + 1}</span><p className="pt-0.5 text-sm leading-5 text-[var(--color-muted)]">{item}</p></div>)}</div></article></section>
    <section className="mt-8 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 shadow-[var(--shadow-card)]"><div><p className="text-sm font-semibold">Active roles</p><p className="mt-1 text-xs text-[var(--color-muted)]">The roles currently available to candidates</p></div>{activeJobs.length ? <div className="mt-5 divide-y divide-[var(--color-border)]">{activeJobs.slice(0, 5).map((job) => <Link key={job.id} to={`/jobs/${job.id}`} className="flex items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><span className="min-w-0"><strong className="block truncate text-sm">{job.title}</strong><span className="mt-1 block text-xs text-[var(--color-muted)]">{applications.filter((application) => application.job_id === job.id).length} applications · {statusLabel(job.status)}</span></span><ChevronRight className="shrink-0 text-[var(--color-muted)]" size={18} aria-hidden="true" /></Link>)}</div> : <p className="mt-5 text-sm text-[var(--color-muted)]">Create and approve a job to begin tracking your hiring workflow.</p>}</section>
    {!jobItems.length && !(candidates.data?.pagination.total ?? 0) && <div className="mt-8"><ReadinessCard /></div>}
  </AppShell>;
}
