import { useQuery } from "@tanstack/react-query";
import { ArrowRight, CheckCircle2, Edit3, GitMerge, Plus } from "lucide-react";
import { candidateTimeline } from "../../features/activity/api";

export function ActivityTimeline({ organizationId, candidateId }: { organizationId: string; candidateId: string }) {
  const query = useQuery({ queryKey: ["activity", organizationId, candidateId], queryFn: () => candidateTimeline(organizationId, candidateId), enabled: !!organizationId && !!candidateId });
  const items = query.data?.items ?? [];
  const iconFor = (label: string) => label.toLowerCase().includes("status") ? <CheckCircle2 size={15} /> : label.toLowerCase().includes("created") ? <Plus size={15} /> : label.toLowerCase().includes("merged") ? <GitMerge size={15} /> : label.toLowerCase().includes("moved") ? <ArrowRight size={15} /> : <Edit3 size={15} />;
  return <section className="mt-8 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Activity timeline</h2><p className="mt-1 text-sm text-[var(--color-muted)]">A chronological record of candidate activity.</p></div>{query.data && <span className="rounded-full bg-[var(--color-sage)] px-3 py-1 text-xs font-semibold text-[var(--color-teal)]">{items.length} events</span>}</div>{query.isLoading && <p className="mt-5 text-sm text-[var(--color-muted)]">Loading activity…</p>}{query.error && <p className="mt-5 text-sm text-[var(--color-red)]">Could not load activity.</p>}{query.data && !items.length && <p className="mt-5 rounded-xl border border-dashed border-[var(--color-border)] p-5 text-sm text-[var(--color-muted)]">No activity recorded yet.</p>}<ol className="relative mt-6 space-y-6 before:absolute before:bottom-3 before:left-4 before:top-3 before:w-px before:bg-[var(--color-border)]">{items.map((event) => <li key={event.id} className="relative flex gap-4"><span aria-hidden="true" className="relative z-10 grid size-8 shrink-0 place-items-center rounded-full border border-[var(--color-border)] bg-[var(--color-surface)] text-[var(--color-navy)] ring-4 ring-[var(--color-surface)]">{iconFor(event.label)}</span><div className="min-w-0 flex-1 pt-0.5"><p className="text-sm leading-5"><strong>{event.actor?.display_name ?? "System"}</strong>{" "}{event.description || event.label}</p><time className="mt-1 block text-xs text-[var(--color-muted)]" title={new Date(event.created_at).toLocaleString()}>{new Intl.RelativeTimeFormat(undefined, { numeric: "auto" }).format(Math.round((new Date(event.created_at).getTime() - Date.now()) / 86400000), "day")}</time>{typeof event.metadata.from_status === "string" && <p className="mt-1 text-xs text-[var(--color-muted)]">{event.metadata.from_status} → {String(event.metadata.to_status)}</p>}</div></li>)}</ol></section>;
}
