import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useCandidateApplications } from "../../features/applications/queries";
import { createCommunication, listCommunications, submitCommunication, updateCommunication, type Communication, type CommunicationType } from "../../features/communications/api";
import { useOrganization } from "../../features/organizations/OrganizationProvider";

const labels: Record<CommunicationType, string> = { interview_follow_up: "Interview Follow-up", next_steps: "Next Steps", offer: "Offer Letter", rejection: "Rejection", hold: "On Hold" };
const templates: Record<CommunicationType, [string, string]> = { interview_follow_up: ["Following up on your interview", "Hello {{candidate_name}},\n\nThank you for taking the time to speak with us about {{job_title}}. We will be in touch with next steps soon."], next_steps: ["Next steps for {{job_title}}", "Hello {{candidate_name}},\n\nWe would like to share the next steps for your application to {{job_title}}."], offer: ["Offer for {{job_title}}", "Hello {{candidate_name}},\n\nWe are pleased to share the details of your offer for {{job_title}}. Please review this draft carefully."], rejection: ["Update on your application", "Hello {{candidate_name}},\n\nThank you for your interest in {{job_title}}. We have decided to continue with other candidates."], hold: ["An update on your application", "Hello {{candidate_name}},\n\nYour application for {{job_title}} is currently on hold. We will share an update when we can."] };
const render = (text: string, name: string) => text.replaceAll("{{candidate_name}}", name).replaceAll("{{job_title}}", "this role").replaceAll(/{{[^}]+}}/g, "");

export function CommunicationsSection({ candidateId, candidateName }: { candidateId: string; candidateName: string }) {
  const { organization } = useOrganization(); const org = organization?.organization.id ?? ""; const { data: applications } = useCandidateApplications(org, candidateId); const client = useQueryClient();
  const [application, setApplication] = useState(""); const [type, setType] = useState<CommunicationType>("next_steps"); const [subject, setSubject] = useState(render(templates.next_steps[0], candidateName)); const [body, setBody] = useState(render(templates.next_steps[1], candidateName)); const [editing, setEditing] = useState<Communication | null>(null);
  const query = useQuery({ queryKey: ["communications", org, application], queryFn: () => listCommunications(org, application), enabled: Boolean(org && application) });
  const save = useMutation({ mutationFn: () => editing ? updateCommunication(org, editing.id, { communication_type: type, subject, body }) : createCommunication(org, application, { communication_type: type, subject, body }), onSuccess: () => { client.invalidateQueries({ queryKey: ["communications", org, application] }); setEditing(null); } });
  const submit = useMutation({ mutationFn: (id: string) => submitCommunication(org, id), onSuccess: () => client.invalidateQueries({ queryKey: ["communications", org, application] }) });
  const chooseType = (value: CommunicationType) => { setType(value); setSubject(render(templates[value][0], candidateName)); setBody(render(templates[value][1], candidateName)); };
  return <section className="mt-8 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 shadow-[var(--shadow-card)]"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Communications</h2><p className="mt-1 text-sm text-[var(--color-muted)]">Prepare private drafts for review. Nothing is sent here.</p></div><select value={application} onChange={(e) => setApplication(e.target.value)} className="hc-select-control max-w-xs text-sm"><option value="">Select application</option>{applications?.items.map((item) => <option key={item.id} value={item.id}>Application · {item.job_id.slice(0, 8)}</option>)}</select></div>{application && <><div className="mt-5 space-y-3">{query.data?.items.map((item) => <article key={item.id} className="rounded-xl border border-[var(--color-border)] bg-[var(--color-elevated)] p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{labels[item.communication_type]}</strong><span className="rounded-full bg-[var(--color-sage)] px-2 py-1 text-xs font-semibold">{item.status.replaceAll("_", " ")}</span></div><p className="mt-2 text-sm">{item.subject}</p><p className="mt-1 text-xs text-[var(--color-muted)]">To {item.recipient_email} · Updated {new Date(item.updated_at).toLocaleDateString()}</p>{["draft", "returned"].includes(item.status) && <button onClick={() => { setEditing(item); setType(item.communication_type); setSubject(item.subject); setBody(item.body); }} className="mt-3 text-sm font-semibold underline">Edit draft</button>}{item.status === "draft" && <button onClick={() => submit.mutate(item.id)} className="ml-4 text-sm font-semibold text-[var(--color-navy)]">Submit for approval</button>}</article>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Communication type<select value={type} onChange={(e) => chooseType(e.target.value as CommunicationType)} className="hc-select-control mt-2"><option value="interview_follow_up">Interview Follow-up</option>{Object.entries(labels).filter(([value]) => value !== "interview_follow_up").map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-medium">Subject<input value={subject} onChange={(e) => setSubject(e.target.value)} className="hc-form-control" /></label></div><label className="mt-4 block text-sm font-medium">Message body<textarea value={body} onChange={(e) => setBody(e.target.value)} rows={7} className="hc-form-control" /></label><div className="mt-4 flex flex-wrap gap-3"><button disabled={save.isPending} onClick={() => save.mutate()} className="hc-primary-action rounded-full">{editing ? "Save draft" : "Create communication"}</button>{editing && <button onClick={() => setEditing(null)} className="rounded-full border border-[var(--color-border)] px-4 py-2 text-sm font-semibold">Cancel</button>}</div></>}</section>;
}
