import { useState } from "react";
import { useLocation } from "react-router-dom";
import { useCandidateMutation, useResumes } from "../../features/candidates/queries";
import { FileDropzone } from "../ui/FileDropzone";

export function ResumeSection({ organizationId, candidateId, editable, embedded = false }: { organizationId: string; candidateId: string; editable: boolean; embedded?: boolean }) {
  const { pathname } = useLocation(); const { data, isLoading } = useResumes(organizationId, candidateId); const mutation = useCandidateMutation(organizationId); const [error, setError] = useState("");
  const canUpload = editable && pathname.endsWith("/edit");
  const choose = (file?: File) => { if (!file) return; if (file.type !== "application/pdf" || !file.name.toLowerCase().endsWith(".pdf") || file.size > 10 * 1024 * 1024) { setError("Choose a PDF file no larger than 10 MiB."); return; } setError(""); mutation.upload.mutate({ id: candidateId, file }); };
  const open = (id: string) => mutation.download.mutate({ candidateId, resumeId: id }, { onSuccess: (result) => window.open(result.download_url, "_blank", "noopener,noreferrer") });
  const content = <>{!embedded && <div><h2 className="text-xl font-semibold">Resume</h2><p className="mt-1 text-sm text-[var(--color-muted)]">{canUpload ? "Upload or replace the candidate’s PDF resume." : "View the candidate’s available resume."}</p></div>}{canUpload && <div className="mt-5"><FileDropzone disabled={mutation.upload.isPending} label={mutation.upload.isPending ? "Uploading resume…" : "Drop a PDF here or click to choose · max 10 MiB"} onFile={choose}/></div>}{error && <p className="mt-3 text-sm text-[var(--color-red)]">{error}</p>}{isLoading && <p className="mt-5 text-sm text-[var(--color-muted)]">Loading resumes…</p>}{data && (data.items.length ? <div className="mt-5 space-y-2">{data.items.map((resume) => <div key={resume.id} className="flex items-center justify-between gap-4 rounded-xl border border-[var(--color-border)] bg-[var(--color-elevated)] p-4"><span className="min-w-0 truncate text-sm font-medium">{resume.original_filename}{resume.is_current && <span className="ml-2 text-xs text-[var(--color-teal)]">Current</span>}</span><button type="button" onClick={() => open(resume.id)} className="shrink-0 text-sm font-semibold text-[var(--color-navy)]">View resume</button></div>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-[var(--color-border)] p-5 text-sm text-[var(--color-muted)]"><strong className="block text-[var(--color-ink)]">No resume uploaded yet.</strong><span className="mt-1 block">{canUpload ? "Upload a PDF to complete this candidate profile." : "A resume can be uploaded from the candidate edit page."}</span></div>)}</>;
  return embedded ? <div className="mt-5">{content}</div> : <section className="mt-7 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 shadow-[var(--shadow-card)] sm:p-7">{content}</section>;
}
