"""add interviewer assignments and feedback
Revision ID: 20260830_feedback
Revises: 20260830_interviews
"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision: str = "20260830_feedback"; down_revision: str | Sequence[str] | None = "20260830_interviews"; branch_labels = None; depends_on = None
def upgrade() -> None:
    op.create_table("interview_assignments", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("organization_id", sa.Uuid(), nullable=False), sa.Column("interview_id", sa.Uuid(), nullable=False), sa.Column("user_id", sa.Uuid(), nullable=False), sa.Column("assigned_by", sa.Uuid(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]), sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"]), sa.ForeignKeyConstraint(["user_id"], ["users.id"]), sa.ForeignKeyConstraint(["assigned_by"], ["users.id"]), sa.UniqueConstraint("interview_id", "user_id"))
    op.create_table("interview_scorecards", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("organization_id", sa.Uuid(), nullable=False), sa.Column("interview_stage_id", sa.Uuid(), nullable=False), sa.Column("title", sa.String(160), nullable=False), sa.Column("instructions", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]), sa.ForeignKeyConstraint(["interview_stage_id"], ["interview_stages.id"]), sa.UniqueConstraint("interview_stage_id"))
    op.create_table("scorecard_criteria", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("scorecard_id", sa.Uuid(), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("description", sa.Text()), sa.Column("position", sa.Integer(), nullable=False), sa.Column("is_required", sa.Boolean(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["scorecard_id"], ["interview_scorecards.id"]), sa.UniqueConstraint("scorecard_id", "position"))
    op.create_table("interview_feedback", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("organization_id", sa.Uuid(), nullable=False), sa.Column("interview_id", sa.Uuid(), nullable=False), sa.Column("reviewer_id", sa.Uuid(), nullable=False), sa.Column("overall_rating", sa.Integer()), sa.Column("recommendation", sa.String(16)), sa.Column("summary", sa.Text(), nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]), sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"]), sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"]), sa.UniqueConstraint("interview_id", "reviewer_id"))
    op.create_table("interview_feedback_items", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("feedback_id", sa.Uuid(), nullable=False), sa.Column("criterion_id", sa.Uuid(), nullable=False), sa.Column("rating", sa.Integer()), sa.Column("notes", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["feedback_id"], ["interview_feedback.id"]), sa.ForeignKeyConstraint(["criterion_id"], ["scorecard_criteria.id"]), sa.UniqueConstraint("feedback_id", "criterion_id"))
def downgrade() -> None: op.drop_table("interview_feedback_items"); op.drop_table("interview_feedback"); op.drop_table("scorecard_criteria"); op.drop_table("interview_scorecards"); op.drop_table("interview_assignments")
